version: "3.9"
services:
  web:
    build: .
    container_name: simple_library
    env_file:
      - .env.dev
    ports:
      - "8000:5000"
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=roman
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=pg_lib
  