version: "3.9"
services:
  web:
    build: .
    container_name: simple_library
    env_file:
      - .env.dev
    ports:
      - "8000:5000"
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  